DROP TABLE IF EXISTS PRODUCT_PRICE;

CREATE TABLE PRODUCT_PRICE (
    BRAND_ID CHAR(1) NOT NULL,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    PRICE_LIST CHAR (1) NOT NULL PRIMARY KEY,
    PRODUCT_ID CHAR(5) NOT NULL,
    PRIORITY SMALLINT NOT NULL,
    PRICE DECIMAL (8, 2) NOT NULL,
    CURR CHAR (3) NOT NULL
);